### ISSUE TITLE
Trade offer 

### ISSUE THREAD

**Issue by d0geda** [bukson/steampy#121]
Hi guys when I make trade offer with only one item it works perfectly, but when I want to add more items from user to the trade it gives me this error
```
Unhandled exception in thread started by <function processingOrder at 0x04344F70>
Traceback (most recent call last):
  File "C:\Users\edast\Desktop\steam python\LvlUpBot\LvlUpBot.py", line 514, in processingOrder
    response = steam_client.make_offer(botsItemsToTrade, itemsToTradeFromUser, partner_id, messages["TRADE_MESSAGE"])
  File "C:\Python27\lib\site-packages\steampy\client.py", line 246, in make_offer
    self._confirm_transaction(response['tradeofferid'])
KeyError: 'tradeofferid'
```

My code for making an offer: 
```
for keysToTrade in range(0, len(klice)):
  item = klice[keysToTrade]
  klicItem = Asset(item,game)
  itemsToTradeFromUser.append(klicItem)
for cardToTrade in range(0, len(steamCards)):
  itemCard = steamCards[cardToTrade]
  itemKarta = Asset(itemCard,steam)
  botsItemsToTrade.append(itemKarta)            
time.sleep(2)
response = steam_client.make_offer(botsItemsToTrade, itemsToTradeFromUser, partner_id, messages["TRADE_MESSAGE"])
time.sleep(3)
```

**Comment by ilya-olkhovskij** [comment]
First of all, as i see you want to send steam trade cards. Did u add steam PredefinedOptions to models?

**Comment by ilya-olkhovskij** [comment]
Did you add Steam PredifinedOptions to models?

And remember that you get only first 2000 items.

**Comment by ilya-olkhovskij** [comment]
And as i know,  trade anyway sends with that exeption.

**Comment by d0geda** [comment]
It sends only one item

**Comment by d0geda** [comment]
It's not even sending the offer
