### ISSUE TITLE
steampy.exceptions.InvalidCredentials at random times

### ISSUE THREAD

**Issue by Phalelashvili** [bukson/steampy#130]
> steampy.exceptions.InvalidCredentials

Hi, this error comes up randomly, and after few attempts steam returns 

> There have been too many login failures from your network in a short time period. Please wait and try again later.

full log:

> Traceback (most recent call last):
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Sinnerman\Desktop\MT\skeleton\views.py", line 55, in deposit
    steam_client.login('tameralkadash', 'tslparoli321', 'mainbot.txt')
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 41, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\login.py", line 25, in login
    self._assert_valid_credentials(login_response)
  File "C:\Users\Sinnerman\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\login.py", line 100, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
steampy.exceptions.InvalidCredentials

any solutions?

**Comment by bukson** [comment]
It is hard problem to debug, it could be from multiple causes. I would need more data to debug.

**Comment by Phalelashvili** [comment]
i don't have more data, it says invalid credentials but i'm sure they're valid, unless the authentication code isn't, maybe code is generated when it's about to expire and login doesn't have enough time to use that

**Comment by lrleo** [comment]
I found that each 2FA code can be used only one time and I was mistakenly trying to login two times without 30 seconds between each session, which leads to the same code being used two times and the login being rejected (even if the code is correct). I don't know if that is the solution for you, but using a simple sleep(30) prevented this error from happening in my program.

**Comment by Phalelashvili** [comment]
> 
> 
> I found that each 2FA code can be used only one time and I was mistakenly trying to login two times without 30 seconds between each session, which leads to the same code being used two times and the login being rejected (even if the code is correct). I don't know if that is the solution for you, but using a simple sleep(30) prevented this error from happening in my program.

that makes sense ty, i'm not facing same issue again because script doesn't have to log in frequently as before, so it has time to regenerate code, fixed it without realizing it lol
