### ISSUE TITLE
get_trade_receipt is raising StopIteration

### ISSUE THREAD

**Issue by SkullTech** [bukson/steampy#138]
Here's an example

```python
>>> client.get_trade_receipt('2197095902291890837')
Traceback (most recent call last):
  File "C:\Users\Sumit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steampy\utils.py", line 22, in texts_between
    start = text.index(begin, stop) + len(begin)
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sumit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steampy\utils.py", line 26, in texts_between
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sumit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steampy\client.py", line 23, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Sumit\AppData\Local\Programs\Python\Python37-32\lib\site-packages\steampy\client.py", line 172, in get_trade_receipt
    for item in texts_between(html, "oItem = ", ";\r\n\toItem"):
RuntimeError: generator raised StopIteration
```

**Comment by SkullTech** [comment]
I investigated this and found out that it's because Python implemented [PEP 0479](https://www.python.org/dev/peps/pep-0479/) starting from v3.7 and it changes how it handles iterators and the `StopIteration` exception.

**Comment by bukson** [comment]
Ok so what would be the solution you want?

**Comment by SkullTech** [comment]
I solved it just by changing the iterator to a normal list. If that's okay for you I can send a pull request.

**Comment by bukson** [comment]
Yes please
