### ISSUE TITLE
Make offer with url error

### ISSUE THREAD

**Issue by puryanms** [bukson/steampy#148]
>>> steam_client.make_offer_with_url([Asset('15006035746', game),Asset('15006035732', game)],[],trade_offer_url="https://steamcommunity.com/tradeoffer/new/?partner=380260898&token=cZcm7-3C",message="Dont Accept pls its test:)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/steampy/client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/steampy/client.py", line 312, in make_offer_with_url
    if response.get('needs_mobile_confirmation'):
AttributeError: 'NoneType' object has no attribute 'get'

what is the problem

**Comment by bukson** [comment]
Hello

Can you paste your code in formatted way and below that the text of error, it will be easier to debug then :)
