### ISSUE TITLE
Hi.Again problems...

### ISSUE THREAD

**Issue by Minecraftboy322** [bukson/steampy#151]
from steampy.client import SteamClient

steam_client = SteamClient('MY_API_KEY')
steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')
With any username/pass/path error.
```
Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/projectfree/steam.py", line 4, in <module>
    steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\steampy\client.py", line 43, in login
    self.steam_guard = guard.load_steam_guard(steam_guard)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\steampy\guard.py", line 16, in load_steam_guard
    return json.loads(steam_guard)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```)

**Comment by bukson** [comment]
Hello, please make sure there is no comma ( , ) at the end of last entry in steamguard file

File should look like this

```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET"
}
```

**NOT** like this
```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET",
}
```
