### ISSUE TITLE
Why i can`t confrim trade

### ISSUE THREAD

**Issue by Minecraftboy322** [bukson/steampy#153]
```
Traceback (most recent call last):
  File "C:/Users/User/Desktop/tradeconfirm.py", line 38, in <module>
    accept = client.accept_trade_offer(trade_id)
  File "C:\Users\User\PycharmProjects\untitled\venv\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\untitled\venv\lib\site-packages\steampy\client.py", line 186, in accept_trade_offer
    trade_offer_state.value))
steampy.exceptions.ApiException: Invalid trade offer state: ConfirmationNeed (9)
```

**Comment by bukson** [comment]
Hello, can you please show you code in formatted way?

**Comment by Minecraftboy322** [comment]
```
username = 'xxxxxxx'
api = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
password = 'xxxxxxxxxxxxxxx'
PATH_TO_STEAMGUARD_FILE = "C:\\Users\\User\\Desktop\\Steamguard\\Steamguard.txt"
client = SteamClient(api)
client.login(username, password, PATH_TO_STEAMGUARD_FILE)
resultfromsteam = requests.get("http://api.steampowered.com/IEconService/GetTradeOffers/v1/?key=xxxxxxxxxxxxxxxxxxxx&get_sent_offers=1&active_only=1").json()
time.sleep(5)
trade_id = resultfromsteam["response"]["trade_offers_sent"][0]["tradeofferid"]
time.sleep(5)
ac = client.accept_trade_offer(trade_id)
```

**Comment by Minecraftboy322** [comment]
sorry, my bad
