### ISSUE TITLE
get_my_inventory returns nothing

### ISSUE THREAD

**Issue by wolfovik** [bukson/steampy#160]
Hello! I've just started using this library today, so may be I'm just doing wrong:

```
from steampy.client import SteamClient
from steampy.utils import GameOptions
game = GameOptions.CS
steam_client = SteamClient('XXXXXXXXXXXXXXXXXXXXXX')
steam_client.login('XXXXXX', 'XXXXXXXX', 'Steamguard.txt')
is_session_alive = steam_client.is_session_alive()
bal = steam_client.get_wallet_balance()
inv = steam_client.get_my_inventory(game, True, 500)
```

but I got 

> Traceback (most recent call last):
  File "E:/Test/venv/Stmpy.py", line 11, in <module>
    inv = steam_client.get_my_inventory(game, True, 500)
  File "E:\Test\venv\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "E:\Test\venv\lib\site-packages\steampy\client.py", line 94, in get_my_inventory
    return self.get_partner_inventory(steam_id, game, merge, count)
  File "E:\Test\venv\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "E:\Test\venv\lib\site-packages\steampy\client.py", line 102, in get_partner_inventory
    if response_dict['success'] != 1:
TypeError: 'NoneType' object is not subscriptable

response_dict is empty. Btw `get_wallet_balance()` works fine
I will be glad to your assumptions))

**Comment by wolfovik** [comment]
Now I got

> steampy.exceptions.InvalidCredentials: There have been too many login failures from your network in a short time period.  Please wait and try again later.

looks like something wrong with my credential file. Sorry
