### ISSUE TITLE
after several successful sentences I get an error cannot find a substring

### ISSUE THREAD

**Issue by geper** [bukson/steampy#171]
after several successful sentences I get an error cannot find a substring
ERROR:
Traceback (most recent call last):
  File "storehouse.py", line 36, in main
    client.accept_trade_offer(offer_id)
  File "C:\Python\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\lib\site-packages\steampy\client.py", line 187, in accept_trade_offer
    partner = self._fetch_trade_partner_id(trade_offer_id)
  File "C:\Python\lib\site-packages\steampy\client.py", line 206, in _fetch_trade_partner_id
    return text_between(offer_response_text, "var g_ulTradePartnerSteamID = '", "';")
  File "C:\Python\lib\site-packages\steampy\utils.py", line 17, in text_between
    start = text.index(begin) + len(begin)
ValueError: substring not found

**Comment by nbordin** [comment]
i am facing the same issue.

Using a very dirty try except, the client accepts the trade correctly.

```python
try:
    client.accept_trade_offer(trade_offer_id)
except ValueError:
     pass
```
