### ISSUE TITLE
Error with create_sell_order

### ISSUE THREAD

**Issue by lyp1noff** [bukson/steampy#177]
I want to sell my steam game card via steampy, but i have an error with confirmation:

```
Traceback (most recent call last):
  File "D:/Code/Python/ASF/test.py", line 12, in <module>
    print(steam_client.market.create_sell_order('837967341', GameOptions.STEAM, "10000"))
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\market.py", line 17, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\market.py", line 108, in create_sell_order
    return self._confirm_sell_listing(assetid)
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\market.py", line 177, in _confirm_sell_listing
    return con_executor.confirm_sell_listing(asset_id)
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\confirmation.py", line 43, in confirm_sell_listing
    confirmation = self._select_sell_listing_confirmation(confirmations, asset_id)
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\confirmation.py", line 105, in _select_sell_listing_confirmation
    confirmation_id = self._get_confirmation_sell_listing_id(confirmation_details_page)
  File "C:\Users\myrrh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\confirmation.py", line 114, in _get_confirmation_sell_listing_id
    scr_raw = scr_raw[scr_raw.index("'confiteminfo', ") + 16:]
ValueError: substring not found
```

Here is my code:

```
from steampy.client import SteamClient
from steampy.utils import GameOptions

with SteamClient(api_key, login, password, steam_guard_file) as client:
    inventory = client.get_my_inventory(GameOptions.STEAM)
    for item in inventory:
        print(inventory[item]['name'], inventory[item]['id'])
        print(client.market.create_sell_order(inventory[item]['id'], GameOptions.STEAM, "10000"))
        break

```

**Comment by kyvees13** [comment]
### You get a response in the form of JSON 
This is a "dict" type, you can find methods for working with it
Your response will be like:
{
'18553531356':  { id = 'some data', name = 'some data' }
'23523524634': { id = 'some data', name = 'some data }
}
To get these values you need to use method
> .keys()

But in your case the solution will be like this by method

```
from steampy.client import SteamClient
from steampy.utils import GameOptions

with SteamClient(api_key, login, password, steam_guard_file) as client:
    inventory = client.get_my_inventory(GameOptions.STEAM)
    for item in inventory.keys():
        print(inventory[item]['name'], inventory[item]['id'])
        print(client.market.create_sell_order(inventory[item]['id'], GameOptions.STEAM, "10000"))
        break
```

### Where item will be: '18553531356' and '23523524634' values

**Comment by Sentexi** [comment]
I had the same issue on a linux machine. For me the solution was to change the parser in `confirmation.py` on line 112 from `'html.parser'` to `'html5lib'`

**Comment by lyp1noff** [comment]
I fixed this with older version of beautifulsoup)

**Comment by lyp1noff** [comment]
Thanks for answers!
