### ISSUE TITLE
I have error with method "create_buy_order"

### ISSUE THREAD

**Issue by kyvees13** [bukson/steampy#178]
### Code:
```
import json
import steampy
from steampy.client import SteamClient
from steampy.guard import generate_one_time_code, generate_confirmation_key, generate_device_id
from steampy.models import GameOptions
from steampy import market
from steampy.models import Currency

API_KEY = "API_KEY"
steamid = "steam_id"
shared_secret_key = "key"
identity_secret_key = "key"
username = "username"
password = "password"
steamguard_data = {
    "steamid": steamid,
    "shared_secret": shared_secret_key,
    "identity_secret": identity_secret_key
}
steamguard_data = json.dumps(steamguard_data)

steam_client = SteamClient(API_KEY)
steam_client.login(username, password, steamguard_data)

wallet_balance = steam_client.get_wallet_balance()
print('MY WALLET BALANCE: {}'.format(wallet_balance))

response = steam_client.market.create_buy_order("AK-47 | Redline (Field-Tested)", "1.57", 1, GameOptions.CS, Currency.RUB)

steam_client.logout()
```

### Traceback:
```
MY WALLET BALANCE: 119.57
True
Traceback (most recent call last):
  File "C:/Users/qq1/PycharmProjects/test/venv/steam.py", line 96, in <module>
    response = steam_client.market.create_buy_order("AK-47 | Redline (Field-Tested)", "1.57", 1, GameOptions.CS, Currency.RUB)
  File "C:\python382\lib\site-packages\steampy\market.py", line 17, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\python382\lib\site-packages\steampy\market.py", line 126, in create_buy_order
    raise ApiException("There was a problem creating the order. Are you using the right currency? success: %s"
steampy.exceptions.ApiException: There was a problem creating the order. Are you using the right currency? success: 2
```
### Method:
```
    @login_required
    def create_buy_order(self, market_name: str, price_single_item: str, quantity: int, game: GameOptions,
                         currency: Currency = Currency.USD) -> dict:
        data = {
            "sessionid": self._session_id,
            "currency": currency.value,
            "appid": game.app_id,
            "market_hash_name": market_name,
            "price_total": str(Decimal(price_single_item) * Decimal(quantity)),
            "quantity": quantity
        }
        headers = {'Referer': "%s/market/listings/%s/%s" % (SteamUrl.COMMUNITY_URL, game.app_id, market_name)}
        response = self._session.post(SteamUrl.COMMUNITY_URL + "/market/createbuyorder/", data,
                                      headers=headers).json()
        if response.get("success") != 1:
            raise ApiException("There was a problem creating the order. Are you using the right currency? success: %s"
                               % response.get("success"))
        return response
```

**Comment by kyvees13** [comment]
### The first time I've ran it in PyCharm, but when I ran it in notepad it worked
