### ISSUE TITLE
 There was a problem creating the order (Currency.RUB)

### ISSUE THREAD

**Issue by skyfeeder** [bukson/steampy#185]
```
highest_order_price of AUG | Contractor (Battle-Scarred) is 0.95
item: AUG | Contractor (Battle-Scarred) put_price is 96 quantity: 20
Traceback (most recent call last):
  File "C:\python\BestSmartOrders\sm_orders.py", line 190, in <module>
    put_order(k, list_orders[k]["highest_order_price"], list_orders[k]["quantity"])
  File "C:\python\BestSmartOrders\sm_orders.py", line 42, in put_order
    response = steam_client.market.create_buy_order(re.sub(r"\n", "", item), put_price, quantity,
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\market.py", line 17, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Александр\AppData\Local\Programs\Python\Python38-32\lib\site-packages\steampy\market.py", line 126, in create_buy_order
    raise ApiException("There was a problem creating the order. Are you using the right currency? success: %s"
steampy.exceptions.ApiException: There was a problem creating the order. Are you using the right currency? success: 8
```

I can manually create a buy order. Before that, I display the balance and a list of already placed orders, there can be no errors related to the login methods. Where can I see the error decryption (success: 8)?

**Comment by skyfeeder** [comment]
I founded the code of success:
`{'success': 8, 'message': 'Sorry! We had trouble hearing back from the Steam servers about your order. Double check whether or not your order has actually been created or filled. If not, then please try again later.'}`
But also I don't understand the reason for the error.
When using Currency.RUB, should I send an integer variable to the function or a string like in your example with Currency.USD?

**Comment by skyfeeder** [comment]
I solved the problem, I had another bot on the VPS, which logged in after authorizing this bot. The balance managed to be displayed, but the subsequent actions with the stim were unsuccessful due to the wrong session.
