### ISSUE TITLE
InvalidCredentials

### ISSUE THREAD

**Issue by Minecraftboy322** [bukson/steampy#188]
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/market/main.py", line 16, in <module>
    client.login("bluefacebaby141", "bluefacebaby142", PATH_TO_STEAMGUARD_FILE)
  File "C:\Users\user\PycharmProjects\market\venv\lib\site-packages\steampy\client.py", line 46, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\user\PycharmProjects\market\venv\lib\site-packages\steampy\login.py", line 23, in login
    self._assert_valid_credentials(login_response)
  File "C:\Users\user\PycharmProjects\market\venv\lib\site-packages\steampy\login.py", line 98, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
steampy.exceptions.InvalidCredentials
A year ago I used your project and everything was fine. However, today I can't sign in to my account.
Login and password are correct, the path to the file is also correct, I have no idea what could be wrong here

**Comment by ldapuser** [comment]
check the steamguard_file. Can you show its structure?

**Comment by Minecraftboy322** [comment]
I rly don`t understd how I fixed it. but.... i just deltd steamguard file and creatd new and it wrks lmao
