### ISSUE TITLE
steampy.exceptions.InvalidCredentials

### ISSUE THREAD

**Issue by vlastof** [bukson/steampy#213]
Here is the code:
from steampy.client import SteamClient 
import configparser

cfg = configparser.ConfigParser()  
cfg.read('cfg.ini')  
steam_client = SteamClient(cfg['Steam']['steam_api']) 
steam_client.login(cfg['Steam']['login'], cfg['Steam']['password'], './steam.txt') 

Every time I get this error:
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\botPy\bot.py", line 7, in <module>
    steam_client.login(cfg['Steam']['login'], cfg['Steam']['password'], './steam.maFile')
  File "C:\Python39\lib\site-packages\steampy\client.py", line 46, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Python39\lib\site-packages\steampy\login.py", line 23, in login
    self._assert_valid_credentials(login_response)
  File "C:\Python39\lib\site-packages\steampy\login.py", line 98, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
steampy.exceptions.InvalidCredentials: The account name or password that you have entered is incorrect.

I have checked everything. I have recreated my 2fa but it doesnt work. Someone please help.

**Comment by vlastof** [comment]
I have solved it myself. If u have the same problem just pay attention to your ini file. The problem was that I was using quotes in my credentials. Just dont write ini file like this:
[Steam]
login = "login"
password = "password"
steam_api = "steamapi"

Write like this:
[Steam]
login = login
password = password
steam_api = steamapi
