### ISSUE TITLE
[Help] Cannot run storehouse.py

### ISSUE THREAD

**Issue by jensenhuangyankai** [bukson/steampy#22]
I cant run it. Using my own script and doing bot.login() also does not work. It constantly gives this error:

This is the donation bot accepting items for free.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/jensen/Desktop/storehouse.py", line 47, in <module>
    main()
  File "/home/jensen/Desktop/storehouse.py", line 21, in main
    client.login(username, password, steamguard_path)
  File "/usr/local/lib/python3.5/dist-packages/steampy/client.py", line 76, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "/usr/local/lib/python3.5/dist-packages/steampy/login.py", line 26, in login
    self._perform_redirects(login_response.json())
  File "/usr/local/lib/python3.5/dist-packages/steampy/login.py", line 81, in _perform_redirects
    parameters = response_dict['transfer_parameters']
KeyError: 'transfer_parameters'

**Comment by bukson** [comment]
Steam servers have problems now. I should make my library throw exception in such situation. I am almost 100% sure its steam fault try by browser

**Comment by jensenhuangyankai** [comment]
Oh lol. I'll try again and update you.
