### ISSUE TITLE
KeyError: 'steamid' problem 

### ISSUE THREAD

**Issue by Dzender** [bukson/steampy#235]
I'm trying to get all items from my inventory using .get_my_inventory() and getting this error.  I'm using path to .mafile (its very importan for my project), but i try also using txt file and its worked:
`{
    "steamid": "*",
    "shared_secret": "*",
    "identity_secret": "*"
}`

all code:

```
import steampy.client, requests
from steampy.utils import GameOptions, get_key_value_from_url, account_id_to_steam_id


client = steampy.client.SteamClient('api')
client.login('log', 'pass', 'D:\\download\\SDA\\maFiles\\account.maFile')
game = GameOptions.CS
my_items = client.get_my_inventory(game)
print(my_items)

```
text of issue:

```
Traceback (most recent call last):
  File "d:\рб\Modern_GUI_PyDracula_PySide6_or_PyQt6-master\main_steam.py", line 9, in <module>
    my_items = client.get_my_inventory(game)
  File "C:\Users\Господин\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Господин\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 93, in get_my_inventory
    steam_id = self.steam_guard['steamid']
KeyError: 'steamid'
```

**Comment by marcu-s** [comment]
Good afternoon Dzender, you have to use a text file since it wont parse a .mafile.
