### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by Mishih** [bukson/steampy#249]
Traceback (most recent call last):
  File "C:\Users\MegaUser\Desktop\BBBoTTT\MyBot.py", line 24, in <module>
    steam_client.login('InfiniteGalaxy', 'strongpassword', 'steam_guard.json') 
  File "C:\Users\MegaUser\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\client.py", line 46, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\MegaUser\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\login.py", line 18, in login
    login_response = self._enter_steam_guard_if_necessary(login_response)
  File "C:\Users\MegaUser\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\login.py", line 81, in _enter_steam_guard_if_necessary
    self.one_time_code = guard.generate_one_time_code(self.shared_secret)
  File "C:\Users\MegaUser\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\guard.py", line 23, in generate_one_time_code
    time_hmac = hmac.new(base64.b64decode(shared_secret), time_buffer, digestmod=sha1).digest()
  File "C:\Users\MegaUser\AppData\Local\Programs\Python\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

Has anyone encountered this problem? I got it after I replaced SteamUrl.STORE_URL with SteamUrl.COMMUNITY_URL

**Comment by woctezuma** [comment]
There seems to be an issue with your `shared_secret`.

**Comment by Mishih** [comment]
Ty
