### ISSUE TITLE
I can't find out the balance of the steam wallet

### ISSUE THREAD

**Issue by Dandelion101** [bukson/steampy#250]
Hello everyone, I get this error when I try to find out the balance of my steam wallet:
```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_Bot_Development\Lots\Module2_steampy.py", line 921, in <module>
    main()
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_Bot_Development\Lots\Module2_steampy.py", line 916, in main
    get_the_balance(steam_client=steam_client)
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_Bot_Development\Lots\Module2_steampy.py", line 778, in get_the_balance
    wallet = get_the_balance_wallet(steam_client=steam_client)
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_Bot_Development\Lots\Module2_steampy.py", line 738, in get_the_balance_wallet
    wallet_balance = steam_client.get_wallet_balance()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 327, in get_wallet_balance
    balance = response_soup.find(id='header_wallet_balance').string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by woctezuma** [comment]
This means `.find(id='header_wallet_balance')` returned `None`.

**Comment by Dandelion101** [comment]
> This means `.find(id='header_wallet_balance')` returned `None`.
I know that Non is back, but he always comes back. How can I fix this error?

**Comment by Faramey** [comment]
I've got the same problem. How to fix it?

**Comment by Faramey** [comment]
> I've got the same problem. How to fix it?

All other functions work fine. Login is successful, but exactly getting the balance does not work, because steam returns unlogged page

**Comment by BilousVladyslav** [comment]
I checked it - sometimes this method works as expected, sometimes Steam can't process the request and returns an error with status `500`. So the issue is not on your side. 

The best way to handle this behavior is to make multiple attempts to call this method after a 3-4 second timeout (you don't want your IP blocked for spam, right?).

**Comment by BilousVladyslav** [comment]
But what has to be done in this function is to check the status code when receiving a response from the server, so that the correct exception can be raised if necessary.

I will add this

**Comment by Faramey** [comment]
> I checked it - sometimes this method works as expected, sometimes Steam can't process the request and returns an error with status `500`. So the issue is not on your side.
> 
> The best way to handle this behavior is to make multiple attempts to call this method after a 3-4 second timeout (you don't want your IP blocked for spam, right?).

I've got status `200`. It just returns with an unlogged steam page. Even if you wait for some time (minutes or half an hour), the answer is always like this. I have no microban for requests.

url = SteamUrl.STORE_URL + '/account/history/'
response = self._session.get(url)
print(response)

<Response [200]>
was_login_executed = {bool} True
balance = None

Faced with this problem only now, before, it worked perfectly.

**Comment by Faramey** [comment]
Well. I fixed that problem with this:
```
url = SteamUrl.STORE_URL + '/market/'
response = self._session.get(url)
response_soup = bs4.BeautifulSoup(response.text, "html.parser")
balance = response_soup.find('a', href='https://store.steampowered.com/account/?snr=1_4_4__global-responsive-menu')
balance = balance.b.text.strip().translate(str.maketrans('', '', '()'))
```

**Comment by Zarkxxxxx** [comment]
> 

thank u so muck for solving this problem XD
