### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by VKamiloss** [bukson/steampy#258]
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kamil\source\repos\test\bot\main.py", line 34, in __init__
    self.steam_client.login(self.username, self.password, self.steamguard)
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\client.py", line 46, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\login.py", line 21, in login
    self._check_for_captcha(login_response)
  File "C:\Users\kamil\AppData\Local\Programs\Python\Python39\lib\site-packages\steampy\login.py", line 86, in _check_for_captcha
    if login_response.json().get('captcha_needed', False):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by BilousVladyslav** [comment]
Here is a very similar issue #246
Hope it could help
