### ISSUE TITLE
needs mobile confirmation for make offer

### ISSUE THREAD

**Issue by Darkinvo** [bukson/steampy#284]
i can loggin to steam account but can not trade  this is error:

Traceback (most recent call last):
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/meti/Desktop/primegame/core-flask/coreflask/app/dota2/views.py", line 38, in decorator
    return f(*args, **kwargs)
  File "/home/meti/Desktop/primegame/core-flask/coreflask/app/dota2/views.py", line 99, in trade_item
    status_trade =  bot.make_offer(
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/steampy/client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/steampy/client.py", line 243, in make_offer
    if response.get('needs_mobile_confirmation'):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by woctezuma** [comment]
Related:
- #246
- #258
- #148 
- #250

**Comment by Darkinvo** [comment]
so how can i do fix this ?

**Comment by woctezuma** [comment]
Hard to tell without more information. Probably https://github.com/bukson/steampy/issues/246#issuecomment-1406202351.
