### ISSUE TITLE
ConfirmationExpected Error

### ISSUE THREAD

**Issue by JamesLewis97** [bukson/steampy#285]
When accepting trades steampy will throw `ConfirmationExpected` but sometimes the trade still goes through.
Is there a known workaround for this while ensuring that the trade completes

```
Traceback (most recent call last):
  File "C:\Users\James\Python\Key Arbitrage\steam_api.py", line 54, in <module>
    steam_client.accept_trade_offer(sell_id)
  File "C:\Users\James\Python\Key Arbitrage\.venv\lib\site-packages\steampy\client.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\James\Python\Key Arbitrage\.venv\lib\site-packages\steampy\client.py", line 198, in accept_trade_offer
    return self._confirm_transaction(trade_offer_id)
  File "C:\Users\James\Python\Key Arbitrage\.venv\lib\site-packages\steampy\client.py", line 211, in _confirm_transaction
    return confirmation_executor.send_trade_allow_request(trade_offer_id)
  File "C:\Users\James\Python\Key Arbitrage\.venv\lib\site-packages\steampy\confirmation.py", line 38, in send_trade_allow_request
    confirmation = self._select_trade_offer_confirmation(confirmations, trade_offer_id)
  File "C:\Users\James\Python\Key Arbitrage\.venv\lib\site-packages\steampy\confirmation.py", line 100, in _select_trade_offer_confirmation
    raise ConfirmationExpected
steampy.exceptions.ConfirmationExpected

```

code raising error

```python
with SteamClient(api_key, username, password, steam_guard_path) as steam_client:
    print(f"Logged in to {username}")

    while True:
        api_offers = steam_client.get_trade_offers()["response"]

        if not are_offers(api_offers):
            print("No offers for now")
            time.sleep(60)
            continue

        print(api_offers)

        buying, selling = process_offers(api_offers)

        print("buying", buying)
        print("selling", selling)

        if len(buying) == 0 or len(selling) == 0:
            print("Not got both buying and selling offers for now")
            time.sleep(60)
            continue

        margins = find_margins(buying, selling)

        trades_to_accept = margins.iloc[0]

        buy_id = trades_to_accept["buy_tradeofferid"]
        buy_scrap = trades_to_accept["buy_scrap_give"]
        sell_id = trades_to_accept["sell_tradeofferid"]
        sell_scrap = trades_to_accept["sell_scrap_receive"]

        print(f"Accepting Sell Offer: {sell_id} for {sell_scrap} scrap")
        steam_client.accept_trade_offer(sell_id)
        print(f"Accepted Sell Offer: {sell_id} for {sell_scrap} scrap")

        print(f"Accepting Buy Offer: {buy_id} for {buy_scrap} scrap")

        steam_client.accept_trade_offer(buy_id)
        print(f"Accepted Buy Offer: {buy_id} for {buy_scrap} scrap")

        time.sleep(60)
```

Any help or pointers greatly appreciated

**Comment by bukson** [comment]
Should be fixed with newest changes
