### ISSUE TITLE
error session login

### ISSUE THREAD

**Issue by mahdikhaligh** [bukson/steampy#290]
Traceback (most recent call last):
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/meti/Desktop/primegame/core-flask/coreflask/app/dota2/views.py", line 44, in decorator
    loop.run_until_complete(bot_login())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/meti/Desktop/primegame/core-flask/coreflask/app/dota2/views.py", line 30, in bot_login
    bot.login(username,password,steamuard)
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/steampy/client.py", line 81, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/steampy/login.py", line 42, in login
    self.set_sessionid_cookies()
  File "/home/meti/Desktop/primegame/core-flask/.env/lib/python3.10/site-packages/steampy/login.py", line 56, in set_sessionid_cookies
    cookie = self.session.cookies.get_dict()[name]
KeyError: 'steamRememberLogin'

**Comment by mahdikhaligh** [comment]
it's working old  version 0.80 but this version 1.0 error for me

**Comment by bukson** [comment]
Can you provide full code?

**Comment by bukson** [comment]
Also probably key names in self.session.cookies.get_dict() would be helpfull

**Comment by mahdikhaligh** [comment]
> Can you provide full code?

of my code or your ?
this is my code with flask:

> 

api = 'apikey-steam'
username = 'username'
password = 'password'
steamuard = '{"steamid": "****","shared_secret": "********","identity_secret": "******"}'
#game = GameOptions('570','2')



def check_login(f):
    @wraps(f)
    def decorator(*args, **kwargs):
        try:
            bot.is_session_alive()
            print("bot is alive")
        except Exception as err:
            asyncio.set_event_loop(asyncio.new_event_loop())
            loop = asyncio.get_event_loop()
            print("bot need to login")
            loop.run_until_complete(bot_login())
            
        return f(*args, **kwargs)
    
    return decorator


class Bot(SteamClient,GameOptions):
    ### to do trade code 
    
    def send_trade(self,_link,assets):
        _list_assets = []
        
        for asset in assets:
            _list_assets.append(Asset(asset,self.DOTA2))
        
        _test = self.make_offer_with_url(_list_assets,[],_link,'test',True)
        print(_test)
    

async def bot_login():
    await asyncio.sleep(0.1)
    global bot
    bot = Bot(api)
    bot.login(username,password,steamuard)
    bot.bot_is_login = True
    print("bot is now login")



@url.route("/dota2",methods=['POST'])
#@check_login
def dota2():
    
    _username = request.json['username']
    _txt = request.json['msg']
    
    user = db.one_or_404(db.select(User).filter_by(username=_username))
    print(user)
    return jsonify({"username":user.username,'txt':_txt})

**Comment by mahdikhaligh** [comment]
> steamRememberLogin

my this key : mybe 'steamRememberLogin' not found in self.session.cookies.get_dict()

**Comment by mahdikhaligh** [comment]
> Also probably key names in self.session.cookies.get_dict() would be helpfull

my this key : mybe 'steamRememberLogin' not found in self.session.cookies.get_dict()

**Comment by bukson** [comment]
Ok fixed in 1.0.1 already avialable in pip
