### ISSUE TITLE
Can't get all the trade offers | Invalid Api

### ISSUE THREAD

**Issue by Dandelion101** [bukson/steampy#297]
I get a similar error every time I use these methods - get_trade_offers, get_trade_offers_summary

```Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_TM_Bot\test.py", line 54, in <module>
    main()
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_TM_Bot\test.py", line 51, in main
    get_all_trades(steam_client)
  File "C:\Users\user\PycharmProjects\pythonProject\Steam_TM_Bot\test.py", line 45, in get_all_trades
    trades = steam_client.get_trade_offers()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 124, in get_trade_offers
    response = self.api_call('GET', 'IEconService', 'GetTradeOffers', 'v1', params).json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\steampy\client.py", line 83, in api_call
    raise InvalidCredentials('Invalid API key')
steampy.exceptions.InvalidCredentials: Invalid API key
```
I've already recreated the Api key but it didn't help, but I can sell items without problems
I'll also confirm any exchange

**Comment by Dandelion101** [comment]
I was using an old version of steampy 0.75, after upgrading to the new version (1.03) the error disappeared
