### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by nstrek** [bukson/steampy#302]
Hi! I'm trying to run inventory.py from examples (https://github.com/bukson/steampy/blob/master/examples/inventory.py) with my account, but I get the following exception:

```
Logging into steam
<Response [200]>
{'success': False, 'requires_twofactor': True, 'message': ''}
{'success': True, 'requires_twofactor': False, 'login_complete': True}
Traceback (most recent call last):
  File "D:\PycharmProjects\SteamTradingResearchNew\inventory.py", line 27, in <module>
    steam_client.login(username, password, steam_guard_path)
  File "D:\PycharmProjects\SteamTradingResearchNew\venv\lib\site-packages\steampy\client.py", line 83, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "D:\PycharmProjects\SteamTradingResearchNew\venv\lib\site-packages\steampy\login.py", line 44, in login
    self._perform_redirects(login_response.json())
  File "D:\PycharmProjects\SteamTradingResearchNew\venv\lib\site-packages\steampy\login.py", line 125, in _perform_redirects
    raise Exception('Cannot perform redirects after login, no parameters fetched')
Exception: Cannot perform redirects after login, no parameters fetched
```

For debug, I modified the login method by adding three print call

![image](https://github.com/bukson/steampy/assets/27504957/5c668192-26cf-4e4a-99af-4e586b7767c4)

Please help me. How can I fix this?

**Comment by Rasul11111** [comment]
Good morning #300
