### ISSUE TITLE
Client.login issue, generate_twofactor_code_for_time

### ISSUE THREAD

**Issue by rozeren** [bukson/steampy#330]
Hello, is there any way to sign in using this code "client.login(username=name,password=password, steam_guard=generate_twofactor_code_for_time("shared secret"))", and if not, how do i do it the right way, it tells me to provide path, but what path, thanks! :)

**Comment by SamuelKollar** [comment]
steam_guard should be the path to your steam_guard file, read the first part at the top of readme.txt to see how to get the steam_guard file

**Comment by rozeren** [comment]
I see, I tried but it still does not work, should I do it like this {
“shared_secret” = “xxx”
} 
Or do I need more text in, for example config.json, is there no easier way to put it in, I can get the code much easier

**Comment by SamuelKollar** [comment]
the steam guard file looks like this ; {"steamid": "xxxxxxxxxxxxxxxxxxx","shared_secret": "xxxxxxxxxxxxxxxxxxxxx","identity_secret": "xxxxxxxxxxxxxxxxxxxxxx"}, if you input that into the login function it should also work I think

**Comment by rozeren** [comment]
Will test that, thank you so so so much!:):)

**Comment by rozeren** [comment]
When trying this, it does still not work "SteamClient.login({"steamid": "XXX","shared_secret": "XXXX","identity_secret": "XXX"})", ofc I changed the values inside to steam64id, my shared secret and identity secret, I get this error : Traceback (most recent call last):
  File "/Users/simonolsson/Desktop/Arb/test.py", line 9, in <module>
    SteamClient.login({"steamid": "76561199586796836","shared_secret": "9JALnCR+TwgfrvR6DrE/C9n6buQ=","identity_secret": "XXX"})
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/steampy/client.py", line 92, in login
    invalid_client_credentials_is_present = None in (self.username, self._password, self.steam_guard_string)
                                                     ^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'username'

**Comment by rozeren** [comment]
Sorry for not being that clear, I also tried this witch does not work : SteamClient.login(username="Name", password="Pass", steam_guard={"steamid": "steam64id","shared_secret": "secret","identity_secret": "secret"})

**Comment by yesworId** [comment]
If you have trouble with steam_guard file. You should create file called steam_guard.json with such data
```
{
    "steamid": "YOUR_STEAM_ID_64",
    "shared_secret": "YOUR_SHARED_SECRET",
    "identity_secret": "YOUR_IDENTITY_SECRET"
}
```
and then login by
```python
client.login(username=name,password=password, steam_guard='steam_guard.json')
```

**Comment by yesworId** [comment]
> Sorry for not being that clear, I also tried this witch does not work : SteamClient.login(username="Name", password="Pass", steam_guard={"steamid": "steam64id","shared_secret": "secret","identity_secret": "secret"})

https://github.com/bukson/steampy?tab=readme-ov-file#usage
