### ISSUE TITLE
Session login issue

### ISSUE THREAD

**Issue by SamuelKollar** [bukson/steampy#331]
### Error I am getting:
Traceback (most recent call last):
  File "Server_steam_client.py", line 321, in <module>
    steam_client.login(username, pswrd, steam_guard)
  File "/usr/local/lib/python3.8/site-packages/steampy/client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "/usr/local/lib/python3.8/site-packages/steampy/login.py", line 39, in login
    finalized_response = self._finalize_login()
  File "/usr/local/lib/python3.8/site-packages/steampy/login.py", line 137, in _finalize_login
    sessionid = self.session.cookies['sessionid']
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.8/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='sessionid', domain=None, path=None"

### My code ( keeps crashing at .login() ):
steam_client = SteamClient(bot_api_key, username=username, password=pswrd, steam_guard=steam_guard)
steam_client.login()

If you have any suggestions on how to fix this please let me know

**Comment by SamuelKollar** [comment]
I just had to wait for a while, all works now.
