### ISSUE TITLE
KeyError: 'refresh_token'

### ISSUE THREAD

**Issue by MaximF39** [bukson/steampy#349]
after fixing https://github.com/bukson/steampy/issues/343#issuecomment-1901125725 I get an error when login(). Tell me how to solve it

```py
Traceback (most recent call last):
  File "C:\Users\max\PycharmProjects\auto_reger_steam\send_trade.py", line 45, in <module>
    send_all_items(login, password, mafile_name, LOGIN_SECURE, STEAM_ID, TOKEN)
  File "C:\Users\max\PycharmProjects\auto_reger_steam\send_trade.py", line 30, in send_all_items
    steam_client.login(username, password, mafile)
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\login.py", line 38, in login
    self._update_steam_guard(login_response)
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\login.py", line 137, in _update_steam_guard
    self._pool_sessions_steam(client_id, request_id)
  File "C:\Users\max\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\login.py", line 145, in _pool_sessions_steam
    self.refresh_token = response.json()['response']['refresh_token']
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
```
```py
response {'response': {'had_remote_interaction': False}}
```

**Comment by MaximF39** [comment]
how cr

**Comment by notdividedeveloper** [comment]
How did you solve it?
