### ISSUE TITLE
Failed to login into account: 'refresh_token'

### ISSUE THREAD

**Issue by OlegAlyeynikov** [bukson/steampy#377]
{"response":{"had_remote_interaction":false}}
Traceback (most recent call last):
  File "/home/csfloat/csgo_float_parser/buy_item/draft.py", line 6, in <module>
    steam_client.login("stoveprofi13", "HX:Q3+7#EC'Ba_C", '/home/csfloat/csgo_float_parser/buy_item/buy_module/credentials/steam_guard.json')
  File "/home/csfloat/csgo_float_parser/buy_item/.venv/lib/python3.10/site-packages/steampy/client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "/home/csfloat/csgo_float_parser/buy_item/.venv/lib/python3.10/site-packages/steampy/login.py", line 38, in login
    self._update_steam_guard(login_response)
  File "/home/csfloat/csgo_float_parser/buy_item/.venv/lib/python3.10/site-packages/steampy/login.py", line 134, in _update_steam_guard
    self._pool_sessions_steam(client_id, request_id)
  File "/home/csfloat/csgo_float_parser/buy_item/.venv/lib/python3.10/site-packages/steampy/login.py", line 142, in _pool_sessions_steam
    self.refresh_token = response.json()['response']['refresh_token']
KeyError: 'refresh_token'

I searched the entire forum regarding this problem but did not find the answer for myself. I tried all the solutions presented on the forum but it didn't help. Maybe someone knows how to update this token? Maybe somehow you can do this manually and then substitute it and use it always? Or is it always updated? I would be grateful for any answer. My one account logs in fine, but the other one gets this error.

**Comment by kostrv** [comment]
Hello, check this #359 
Same problem, and good solution

**Comment by deucebucket** [comment]
## Working Alternative: pysteamauth

For anyone still hitting this issue - the root cause is that Steam's authentication API now requires **protobuf-encoded requests**, but steampy sends traditional form fields.

**`pysteamauth`** is a library that uses the correct protobuf format and works with Steam's current auth:

```bash
pip install pysteamauth
```

```python
import asyncio
from pysteamauth.auth import Steam

async def login():
    steam = Steam(
        login='your_username',
        password='your_password',
        shared_secret='your_shared_secret',  # from maFile
        identity_secret='your_identity_secret',  # from maFile
    )
    await steam.login_to_steam()
    print(f"Logged in! SteamID: {steam._steamid}")
    
    # Use steam._requests for authenticated API calls
    # e.g., steam._requests.text(method='GET', url='...')

asyncio.run(login())
```

This uses the same credentials/maFile format but handles the protobuf encoding correctly.

**Note:** pysteamauth is async, so you'll need to adapt your code accordingly. It doesn't have steampy's market/trading helpers built-in, but you can make authenticated requests using `steam._requests` after login.

Hope this helps someone!
