### ISSUE TITLE
buy_item can't start

### ISSUE THREAD

**Issue by laifodes** [bukson/steampy#396]
from steampy.client import SteamClient
from steampy.models import Currency, GameOptions
import json

with open('account_info.txt', 'r') as acc:
    login, password, api_key, steam_id, shared_secret, identity_secret = acc.read().split(',')

steam_client = SteamClient(api_key=api_key)

# steam_guard JSON
steam_guard_data = json.dumps({
    "steamid": steam_id,
    "shared_secret": shared_secret,
    "identity_secret": identity_secret
})

with SteamClient(api_key, login, password, steam_guard_data) as client:
    print(steam_client.is_session_alive())
    response = client.market.buy_item('R8 Revolver | Bone Mask (Well-Worn)', '4911820044455752514', 93, 12,
                                        GameOptions.CS, Currency.RUB)

    print(response)
    
 
 
 ```Traceback (most recent call last):
  File "D:\Programming\Python\steamautobuy\testbuy3.py", line 17, in <module>
    with SteamClient(api_key, login, password, steam_guard_data) as client:
  File "D:\Programming\Python\steamautobuy\Lib\site-packages\steampy\client.py", line 126, in __enter__
    self.login(self.username, self._password, self.steam_guard_string)
  File "D:\Programming\Python\steamautobuy\Lib\site-packages\steampy\client.py", line 110, in login
    LoginExecutor(self.username, self._password, self.steam_guard['shared_secret'], self._session).login()
  File "D:\Programming\Python\steamautobuy\Lib\site-packages\steampy\login.py", line 38, in login
    self._update_steam_guard(login_response)
  File "D:\Programming\Python\steamautobuy\Lib\site-packages\steampy\login.py", line 117, in _update_steam_guard
    client_id = login_response.json()['response']['client_id']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'client_id'```
![photo_2024-07-06_13-49-50](https://github.com/bukson/steampy/assets/71565840/e811a432-d66c-4770-8460-0ab144d198fb)
The item is on the market, but you can’t buy it.

**Comment by Aarab228** [comment]
забанило айпи из-за частых запросов (я забыл за них и только что свой тоже забанил :) )

**Comment by p-arbuzov** [comment]
Коллеги, кто шарит сколько по новым ограничениям можно запросов сейчас делать?

**Comment by Aarab228** [comment]
> Коллеги, кто шарит сколько по новым ограничениям можно запросов сейчас делать?

опять новые ограничения ввели? Раньше не более 20 запросов в минуту было (1 запрос раз в ~4 секунды)

**Comment by p-arbuzov** [comment]
> > Коллеги, кто шарит сколько по новым ограничениям можно запросов сейчас делать?
> 
> опять новые ограничения ввели? Раньше не более 20 запросов в минуту было (1 запрос раз в ~4 секунды)

Да, как будто где-то месяц назад или меньше все стали чаще 429 код ответа ловить за слишком частые запросы.

**Comment by laifodes** [comment]
> забанило айпи из-за частых запросов (я забыл за них и только что свой тоже забанил :) )

нет, это не так, там другая ошибка.

**Comment by Onione-Tamiko** [comment]
@laifodes и че делать?

**Comment by Aarab228** [comment]
> > забанило айпи из-за частых запросов (я забыл за них и только что свой тоже забанил :) )
> 
> нет, это не так, там другая ошибка.

ну так какая?
