### ISSUE TITLE
make_offer_with_url

### ISSUE THREAD

**Issue by vladislavzorin** [bukson/steampy#397]
```
#Traceback (most recent call last):
  File "C:\Users\flesh\OneDrive\Рабочий стол\fermaMax\senderItems.py", line 109, in sendAllItems
    steam_client.make_offer_with_url(assets, [], trade)
  File "C:\Users\flesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\utils.py", line 23, in func_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\flesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\steampy\client.py", line 397, in make_offer_with_url
    if response.get('needs_mobile_confirmation', False):
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:
```

In _make_offer_with_url_,  _response = self._session.post(url, data=params, headers=headers).json()_ is **None**

**Comment by vladislavzorin** [comment]
Response code 401

**Comment by Aarab228** [comment]
> Response code 401

login first for do this

**Comment by Aarab228** [comment]
> > Response code 401
> 
> login first to do this

**Comment by Darkinvo** [comment]
i do login  but i have this error 
```    
    if response.get('needs_mobile_confirmation', False):
       ^^^^^^^^^^^^ 
     AttributeError: 'NoneType' object has no attribute 'get'

**Comment by delta325** [comment]
> i do login but i have this error
> 
> ```
>     if response.get('needs_mobile_confirmation', False):
>        ^^^^^^^^^^^^ 
>      AttributeError: 'NoneType' object has no attribute 'get'
> ```

Do you login with cookies or saved session? Or you just login with login/password/guard?

**Comment by Darkinvo** [comment]
> > i do login but i have this error
> > ```
> >     if response.get('needs_mobile_confirmation', False):
> >        ^^^^^^^^^^^^ 
> >      AttributeError: 'NoneType' object has no attribute 'get'
> > ```
> 
> Do you login with cookies or saved session? Or you just login with login/password/guard?

i try with both cookies and manual login (user,pass,guard) i can get my inventory bot but i can not make offer trade this show error :
> > ```
> >     if response.get('needs_mobile_confirmation', False):
> >        ^^^^^^^^^^^^ 
> >      AttributeError: 'NoneType' object has no attribute 'get'
> > ```

**Comment by delta325** [comment]
> > > i do login but i have this error
> > > ```
> > >     if response.get('needs_mobile_confirmation', False):
> > >        ^^^^^^^^^^^^ 
> > >      AttributeError: 'NoneType' object has no attribute 'get'
> > > ```
> > 
> > 
> > Do you login with cookies or saved session? Or you just login with login/password/guard?
> 
> i try with both cookies and manual login (user,pass,guard) i can get my inventory bot but i can not make offer trade this show error :
> 
> > > ```
> > >     if response.get('needs_mobile_confirmation', False):
> > >        ^^^^^^^^^^^^ 
> > >      AttributeError: 'NoneType' object has no attribute 'get'
> > > ```
this library confirms trades for you, you didn't provide Steam_Guard that's why you face this exception.
your code looks like this:

steam_client = SteamClient(api_key username=username, login_cookies=community_cookies)

but in order to confirm trades you should use:

steam_client = SteamClient(api_key username=username, login_cookies=community_cookies, steam_guard = steamguard_path)

or you can comment some part of the library in order to disable confirmations

**Comment by Darkinvo** [comment]
> > > > i do login but i have this error
> > > > ```
> > > >     if response.get('needs_mobile_confirmation', False):
> > > >        ^^^^^^^^^^^^ 
> > > >      AttributeError: 'NoneType' object has no attribute 'get'
> > > > ```
> > > 
> > > 
> > > Do you login with cookies or saved session? Or you just login with login/password/guard?
> > 
> > 
> > i try with both cookies and manual login (user,pass,guard) i can get my inventory bot but i can not make offer trade this show error :
> > > > ```
> > > >     if response.get('needs_mobile_confirmation', False):
> > > >        ^^^^^^^^^^^^ 
> > > >      AttributeError: 'NoneType' object has no attribute 'get'
> > > > ```
> 
> this library confirms trades for you, you didn't provide Steam_Guard that's why you face this exception. your code looks like this:
> 
> steam_client = SteamClient(api_key username=username, login_cookies=community_cookies)
> 
> but in order to confirm trades you should use:
> 
> steam_client = SteamClient(api_key username=username, login_cookies=community_cookies, steam_guard = steamguard_path)
> 
> or you can comment some part of the library in order to disable confirmations

when i used with manual login without cookies 'make_offer_with_url' it's fine , but when i use login with cookie again 'None Response'  , this my code i using :
```
 __username = '####'
 __password = '####'
 __steamguard = 'account_steam.json'
 __apikey = '#####'
    
    
 _cookies_steam = Tools.read_json("cookies_steam.json","steam")
    
 if _cookies_steam['next_login'] is None or dt.datetime.strptime(_cookies_steam['next_login'],"%Y-%m-%d %H:%M:%S.%f") < dt.datetime.now():
    bot = SteamClient(__apikey)
    # do login
    try:    
        bot.login(__username,__password,__steamguard)
    except Exception as error:
        print(error)
        return
        
    cookies_after_login_bot = bot._session.cookies.get_dict()
    cookies_after_login_bot['next_login'] = f"{dt.datetime.now() + dt.timedelta(30)}"
    Tools.update_json("cookies_steam.json","steam",cookies_after_login_bot)
        
 else:
        
    print("loggin with cookies ....")
    bot = SteamClient(
        api_key=__apikey,
        username=__username,
        steam_guard=__steamguard,
        login_cookies=_cookies_steam
    )

    
list_ready = []
    
list_ready.append(Asset("123456789",GameOptions.DOTA2))
response_trade = bot.make_offer_with_url(
    list_ready,
    [],
    "https://steamcommunity.com/tradeoffer/new/?partner=123456789&token=dkfgfsef",
    "",
    True,
    True
)
print(response_trade)
```
