### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by d0geda** [bukson/steampy#40]
Well when I want to start my program this error pops up
```
Traceback (most recent call last):
  File "C:/Users/edast/Desktop/steam python/fetching_inv.py", line 1, in <module>
    from steampy.client import SteamClient
  File "C:\Python27\lib\site-packages\steampy\client.py", line 23
    def __init__(self, asset_id: str, game: GameOptions, amount: int = 1) -> None:
                               ^
SyntaxError: invalid syntax
```

My code
```
from steampy.client import SteamClient
from steampy.utils import GameOptions
from getpass import getpass

userName = raw_input("Steam name: ")
password = getpass("Password: ")
authCode = raw_input("Steam 2FA Code: ")

steam_client = SteamClient("Api key")
steam_client.login(userName, password, authCode)
partner_id = "FriendsId"
game = GameOptions.CS
partner_items = steam_client.get_partner_inventory(partner_id, game)
print(partner_items)
steam_client.logout()
```

**Comment by bukson** [comment]
Python > 3.5 is required, you are using 2.7, use python 3
