### ISSUE TITLE
Login with cookie 

### ISSUE THREAD

**Issue by yeqwer** [bukson/steampy#422]
Does logging in via cookies work? 
If so, what should the cookie data look like? 
My goal is to log into an account with only a refresh token. Thanks for any information :D

**Comment by jacks-sam1010** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implemented a new method to allow logging in using a refresh token. Modified the LoginExecutor class to support this new login method. Updated the login method to use the new functionality when a refresh token is provided.

You can review changes in this commit: https://github.com/jacks-sam1010/bukson-steampy-422/commit/edfc68966fe968ac40825a303ee6ee7e63bfb26e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by yeqwer** [comment]
Unfortunately this solution doesn't work.

**Comment by yeqwer** [comment]
Maybe I can log in not directly with refresh token, but with cookies, which I will get with steam-session module for node js from [DoctorMcKay](https://github.com/DoctorMcKay). But I would like to know which cookie dict I should give.

**Comment by bukson** [comment]
SteamClient supports login_cookies parameter, that allows login by cookies

**Comment by delta325** [comment]
I'm experiencing the same problem, login with cookies method works fine, but the session dies after 24 hours and you have to login again. It creates another device in the list of authorized devices and if you are unlucky as me, you will get your account locked when you'll try to make_offer_with_url method (steam says it suspects account was stolen, lol)

**Comment by yeqwer** [comment]
My problem is that i want to login with cookie but i don't know how cookie dict should look like. i would be very grateful if you show an example of cookie dict. I understand that if i login using steamid, shared_secret, identity_secret and then save cookie and login with cookie in future, it will work. But i don't want to use shared_secret and identity_secret.

**Comment by delta325** [comment]
> My problem is that i want to login with cookie but i don't know how cookie dict should look like. i would be very grateful if you show an example of cookie dict. I understand that if i login using steamid, shared_secret, identity_secret and then save cookie and login with cookie in future, it will work. But i don't want to use shared_secret and identity_secret.

My cookies dict looks like this

{"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxx"}

The problem is that they last only 24 hours.
Do you have any idea how to login without creating new device everyday?

**Comment by yeqwer** [comment]
> > Моя проблема в том, что я хочу войти с помощью cookie, но не знаю, как должен выглядеть cookie dict. Я был бы очень признателен, если бы вы показали пример cookie dict. Я понимаю, что если я войду, используя steamid, shared_secret, identity_secret, а затем сохраню cookie и войду с cookie в будущем, это сработает. Но я не хочу использовать shared_secret и identity_secret.
> 
> Мой словарь cookie выглядит так {"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxx"} Проблема в том, что они существуют всего 24 часа. Есть ли у вас идеи, как войти в систему, не создавая новое устройство каждый день?

As far as I know a session for 24 hours is refreshed with refresh_token, and you can refresh it in the module for node.js I mentioned above or you can refresh it manually :D

**Comment by yeqwer** [comment]
I don't know about adding a new device, nor do I know what's wrong with it or how to avoid it. I think that's how steam works.

**Comment by yeqwer** [comment]
> > Моя проблема в том, что я хочу войти с помощью cookie, но не знаю, как должен выглядеть cookie dict. Я был бы очень признателен, если бы вы показали пример cookie dict. Я понимаю, что если я войду, используя steamid, shared_secret, identity_secret, а затем сохраню cookie и войду с cookie в будущем, это сработает. Но я не хочу использовать shared_secret и identity_secret.
> 
> Мой словарь cookie выглядит так
> 
> {"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxxx"}
> 
> Проблема в том, что они длятся всего 24 часа. Есть ли у вас идеи, как войти, не создавая новое устройство каждый день?

And you got those dictionary cookies just from your browser?

**Comment by delta325** [comment]
> > > Моя проблема в том, что я хочу войти с помощью cookie, но не знаю, как должен выглядеть cookie dict. Я был бы очень признателен, если бы вы показали пример cookie dict. Я понимаю, что если я войду, используя steamid, shared_secret, identity_secret, а затем сохраню cookie и войду с cookie в будущем, это сработает. Но я не хочу использовать shared_secret и identity_secret.
> > 
> > 
> > Мой словарь cookie выглядит так {"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxx"} Проблема в том, что они существуют всего 24 часа. Есть ли у вас идеи, как войти в систему, не создавая новое устройство каждый день?
> 
> As far as I know a session for 24 hours is refreshed with refresh_token, and you can refresh it in the module for node.js I mentioned above or you can refresh it manually :D

Yes, I've already read about node. js, maybe we can implement their solution here in Python

**Comment by delta325** [comment]
> > > Моя проблема в том, что я хочу войти с помощью cookie, но не знаю, как должен выглядеть cookie dict. Я был бы очень признателен, если бы вы показали пример cookie dict. Я понимаю, что если я войду, используя steamid, shared_secret, identity_secret, а затем сохраню cookie и войду с cookie в будущем, это сработает. Но я не хочу использовать shared_secret и identity_secret.
> > 
> > 
> > Мой словарь cookie выглядит так
> > {"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxxx"}
> > Проблема в том, что они длятся всего 24 часа. Есть ли у вас идеи, как войти, не создавая новое устройство каждый день?
> 
> And you got those dictionary cookies just from your browser?

No, you can get your cookies after you login with client.login method and then obtain your cookies with client._session.cookies.get_dict("steamcommunity") method

**Comment by yeqwer** [comment]
But I don't want to use shared_secret and identity_secret for login. I would like to log in immediately with a cookie.

**Comment by yeqwer** [comment]
> > > > Моя проблема в том, что я хочу войти с помощью cookie, но не знаю, как должен выглядеть cookie dict. Я был бы очень признателен, если бы вы показали пример cookie dict. Я понимаю, что если я войду, используя steamid, shared_secret, identity_secret, а затем сохраню cookie и войду с cookie в будущем, это сработает. Но я не хочу использовать shared_secret и identity_secret.
> > > 
> > > 
> > > Мой словарь cookie выглядит так {"sessionid": "xxxxxxxxxxx", "steamCountry": "xxxxxxxxxxx", "steamLoginSecure": "xxxxxxxxxxxx", "steamRefresh_steam": "xxxxxxxxxxxxxx"} Проблема в том, что они существуют всего 24 часа. Есть ли у вас идеи, как войти в систему, не создавая новое устройство каждый день?
> > 
> > 
> > As far as I know a session for 24 hours is refreshed with refresh_token, and you can refresh it in the module for node.js I mentioned above or you can refresh it manually :D
> 
> Yes, I've already read about node. js, maybe we can implement their solution here in Python

I don't know exactly how the update works. But I do know that this module works very well and I suggest you to look at its code. 
I would use only this node.js module myself, but it doesn't have an item purchase function. I've been trying to write add-ons to this module, but I haven't finished yet.

**Comment by delta325** [comment]
> But I don't want to use shared_secret and identity_secret for login. I would like to log in immediately with a cookie.

You can login without shared_secret as I said, I meant if you want to obtain cookies you will have to use shared_secret. 
If you already have cookies, you can login with you api_key and username and you cookies (there is a method for it)

**Comment by yeqwer** [comment]
I'm running to try it! :D

**Comment by delta325** [comment]
> I'm running to try it! :D

I wish you a good luck. 
Small tip from me: if you'll login with only cookies, you won't be able to confirm trades, and some exceptions may occur. You will have to catch them.

**Comment by yeqwer** [comment]
> > Бегу пробовать! :D
> 
> Желаю вам удачи. Небольшой совет от меня: если вы войдете только с куками, вы не сможете подтверждать сделки, и могут возникнуть некоторые исключения. Вам придется их ловить.

Thanks for the tip, I thought I had to confirm, but I only need to buy items ;D

**Comment by bukson** [comment]
If someone can implement refresh cookie method, I will gladly merge it and release new version.

**Comment by yeqwer** [comment]
Unfortunately I get an error of this format when I use my cookies from my browser: 

`Traceback (most recent call last):
  File "/Users/yeqwer/Projects/steam_sculp/steam_controller_py/login2.py", line 18, in <module>
    client = SteamClient(api_key=API_KEY, username=USER_NAME, login_cookies=LOGIN_COOKIES)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 61, in __init__
    self.set_login_cookies(login_cookies)
  File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 79, in set_login_cookies
    self.steam_guard = {'steamid': str(self.get_steam_id())}
                                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/utils.py", line 26, in func_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 88, in get_steam_id
    raise ValueError(f'Invalid steam_id: {steam_id}')
ValueError: Invalid steam_id: None`

I used the code from the example in the documentation:

`from steampy.client import SteamClient
from dotenv import load_dotenv
import os

load_dotenv()

API_KEY = os.getenv("API_KEY")
USER_NAME = os.getenv("USER_NAME")
LOGIN_COOKIES = {
  "sessionid": os.getenv("sessionid"),
  "steamCounry": os.getenv("steamCountry"),
  "steamLoginSecure": os.getenv("steamLoginSecure"),
  "steamRefresh_steam": os.getenv("steamRefresh_steam")
  }

client = SteamClient(api_key=API_KEY, username=USER_NAME, login_cookies=LOGIN_COOKIES)

print(client.was_login_executed)

`

**Comment by yeqwer** [comment]
Unfortunately I get an error of this format when I use my cookies from my browser:
 
`Traceback (most recent call last): File "/Users/yeqwer/Projects/steam_sculp/steam_controller_py/login2.py", line 18, in <module> client = SteamClient(api_key=API_KEY, username=USER_NAME, login_cookies=LOGIN_COOKIES) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 61, in __init__ self.set_login_cookies(login_cookies) File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 79, in set_login_cookies self.steam_guard = {'steamid': str(self.get_steam_id())} ^^^^^^^^^^^^^^^^^^^ File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/utils.py", line 26, in func_wrapper return func(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/yeqwer/.pyenv/versions/3.12.7/envs/steam-sculp/lib/python3.12/site-packages/steampy/client.py", line 88, in get_steam_id raise ValueError(f'Invalid steam_id: {steam_id}') ValueError: Invalid steam_id: None`
 
I used the code from the example in the documentation:
 
```
from steampy.client import SteamClient from dotenv import load_dotenv import os

load_dotenv()
 
API_KEY = os.getenv("API_KEY") USER_NAME = os.getenv("USER_NAME") LOGIN_COOKIES = { "sessionid": os.getenv("sessionid"), "steamCounry": os.getenv("steamCountry"), "steamLoginSecure": os.getenv("steamLoginSecure"), "steamRefresh_steam": os.getenv("steamRefresh_steam") }

client = SteamClient(api_key=API_KEY, username=USER_NAME, login_cookies=LOGIN_COOKIES)

print(client.was_login_executed)

```

**Comment by yeqwer** [comment]
I have seen a similar error discussed in issues github, but haven't found a solution. Maybe I'm using the wrong cookie format? 
@bukson

**Comment by delta325** [comment]
> I have seen a similar error discussed in issues github, but haven't found a solution. Maybe I'm using the wrong cookie format? @bukson

Are you sure you use cookies from correct account? 
There must be your steam_id there, compare them

**Comment by yeqwer** [comment]
> > I have seen a similar error discussed in issues github, but haven't found a solution. Maybe I'm using the wrong cookie format? @bukson
> 
> Are you sure you use cookies from correct account? There must be your steam_id there, compare them

steamid is absolutely accurate. As I understand it steamLoginSecure consists of steamid + access_token

**Comment by delta325** [comment]
> > > I have seen a similar error discussed in issues github, but haven't found a solution. Maybe I'm using the wrong cookie format? @bukson
> > 
> > 
> > Are you sure you use cookies from correct account? There must be your steam_id there, compare them
> 
> steamid is absolutely accurate. As I understand it steamLoginSecure consists of steamid + access_token

I load my cookies as a json file and it works. The problem is in your code I guess. And make sure you use cookies from steamcommunity, not the steam.powered

**Comment by yeqwer** [comment]
> I load my cookies as a json file and it works. The problem is in your code I guess. And make sure you use cookies from steamcommunity, not the steam.powered

You're right, I fixed that error, but when I buy a buy item, an error pops up that says I must use the login method. Am I correct that cookie login does not support buying items?

**Comment by yeqwer** [comment]
I've seen an implementation of buying items where the person only gives a refresh_token. How did you implement it... :D

**Comment by delta325** [comment]
> > I load my cookies as a json file and it works. The problem is in your code I guess. And make sure you use cookies from steamcommunity, not the steam.powered
> 
> You're right, I fixed that error, but when I buy a buy item, an error pops up that says I must use the login method. Am I correct that cookie login does not support buying items?

I use Steampy only to accept and to send trades, I didn't work with buying items xD
You can read docs if something is unclear

**Comment by yeqwer** [comment]
> I use Steampy only to accept and to send trades, I didn't work with buying items xD You can read docs if something is unclear

The documentation says exactly that I should use the .login() method before purchasing.
That said, I'm definitely logged into the account, just like with shared and identity, but I can't buy items. 

Can you please tell me if this is possible or not? @bukson
