### ISSUE TITLE
InvalidCredentials with empty message while logging

### ISSUE THREAD

**Issue by MichaelPak** [bukson/steampy#53]
In response to two-factor authorization, I get an error with a mixed message. Here's the log:
```
2017.05.15 16:15:48 [app.DEBUG][26745 140737041318848] Response for steam auth: 
{"success":false,"requires_twofactor":true,"message":""} (login.py:28)
2017.05.15 16:15:50 [app.DEBUG][26745 140737041318848] Response for steam two-factor auth: 
{"success":false,"requires_twofactor":true,"message":""} (login.py:31)

```
What am I doing wrong?

**Comment by MichaelPak** [comment]
I think that Steam has protection when working with several bots from one server. I added the proxy server address in the authorization request and it all worked. Am i right?

**Comment by Zwork101** [comment]
Yeah, it will start to block the IP. A proxy should work just fine

**Comment by bukson** [comment]
There is no additional message? I could raise an exception but don't know how to check for it

**Comment by MichaelPak** [comment]
Message field is empty. You can try to authorize several bots from your local server.

**Comment by MichaelPak** [comment]
Message field is empty. You can try to authorize several bots from your local server.

**Comment by MichaelPak** [comment]
The error can be reproduced in this way:
`cl1 = SteamClient(bot1.steam_api_key)
cl1.login(bot1.login, bot1.password, bot1.shared_secret, bot1.identity_secret, bot1.steam_id)
cl2 = SteamClient(bot2.steam_api_key)
cl2.login(bot2.login, bot2.password, bot2.shared_secret, bot2.identity_secret, bot2.steam_id)
cl1.isLoggedIn
True
cl2.isLoggedIn
True
cl3 = SteamClient(bot3.steam_api_key)
cl3.login(bot3.login, bot3.password, bot3.shared_secret, bot3.identity_secret, bot3.steam_id)
cl1.login(bot1.login, bot1.password, bot1.shared_secret, bot1.identity_secret, bot1.steam_id)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/client.py", line 81, in login
    self.steam_guard['identity_secret'] = identity_secret
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 32, in login
    self._assert_valid_credentials(login_response)
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 94, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
packages.steampy.login.InvalidCredentials
cl2.login(bot2.login, bot2.password, bot2.shared_secret, bot2.identity_secret, bot2.steam_id)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/client.py", line 81, in login
    self.steam_guard['identity_secret'] = identity_secret
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 32, in login
    self._assert_valid_credentials(login_response)
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 94, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
packages.steampy.login.InvalidCredentials
`

**Comment by MichaelPak** [comment]
It's problem not in ban by IP address:

```>>> sc = SteamClient(api_key=bot.steam_api_key)
>>> sc = SteamClient(api_key=bot.steam_api_key)
>>> sc._session.proxies
{}
>>> sc.login(
...     username=bot.login,
...     password=bot.password,
...     shared_secret=bot.shared_secret,
...     identity_secret=bot.identity_secret,
...     steamid=bot.steam_id
... )
>>> sc.isLoggedIn
True
>>> sc.login(
...     username=bot.login,
...     password=bot.password,
...     shared_secret=bot.shared_secret,
...     identity_secret=bot.identity_secret,
...     steamid=bot.steam_id
... )
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/client.py", line 83, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 32, in login
    self._assert_valid_credentials(login_response)
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 94, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
packages.steampy.login.InvalidCredentials
>>> sc._session.proxies.update({
...     'https': 'https://{}:{}@{}'.format(
...         settings.PROXY_AUTH.get('username'),
...         settings.PROXY_AUTH.get('password'),
...         bot.proxy
...     )
... })
>>> sc.login(
...     username=bot.login,
...     password=bot.password,
...     shared_secret=bot.shared_secret,
...     identity_secret=bot.identity_secret,
...     steamid=bot.steam_id
... )
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/client.py", line 83, in login
    LoginExecutor(username, password, self.steam_guard['shared_secret'], self._session).login()
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 32, in login
    self._assert_valid_credentials(login_response)
  File "/Users/michaelpak/Projects/roulette/tradein/packages/steampy/login.py", line 94, in _assert_valid_credentials
    raise InvalidCredentials(login_response.json()['message'])
packages.steampy.login.InvalidCredentials
```
