### ISSUE TITLE
Get trade status info

### ISSUE THREAD

**Issue by MichaelPak** [bukson/steampy#54]
How to find out if user has accepted trade?

**Comment by MichaelPak** [comment]
Player did not accept the order

```
>>> steam_client.get_trade_offer(tradeofferid)['response']['offer']
{
    'tradeofferid': '2130373359',
    ...,
    'trade_offer_state': 2,
}
```
And player has accepted trade:

```
>>> steam_client.get_trade_offer(tradeofferid)['response']['offer']
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/path/to/steampy/client.py", line 171, in get_trade_offer
    descriptions = {get_description_key(offer): offer for offer in response['response']['descriptions']}
KeyError: 'descriptions'
```
'case from steam comes empty response.

**Comment by bukson** [comment]
Have you tried  steam_client.get_trade_offer(tradeofferid, false)['response']['offer']

so getting offer without merging?
