### ISSUE TITLE
So i trying to import steam.client

### ISSUE THREAD

**Issue by vRevolver** [bukson/steampy#88]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python34\lib\site-packages\steampy\client.py", line 10, in <module>
    from steampy.market import SteamMarket
  File "D:\Python34\lib\site-packages\steampy\market.py", line 68
    listings["sell_listings"] = {**listings["sell_listings"], **listings_2["sell_listings"]}
                                  ^
SyntaxError: invalid syntax`

**Comment by Ermans** [comment]
You are using Python 3.4.
This library uses Python 3.5
