### ISSUE TITLE
tf2 is broken

### ISSUE THREAD

**Issue by mninc** [bukson/steampy#98]
```py
Traceback (most recent call last):
  File "C:/Users/-/Documents/test2.py", line 30, in <module>
    my_items = client.get_my_inventory(game)
  File "C:\Users\-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 22, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\-\AppData\Local\Programs\Python\Python36-32\lib\site-packages\steampy\client.py", line 77, in get_my_inventory
    game.app_id + '/' + \
AttributeError: 'tuple' object has no attribute 'app_id'
```

when trying to get tf2 inventory using the usual method. also happens when sending a trade (not using the get inventory method)

**Comment by bukson** [comment]
Works with me, anyone with same problem?

**Comment by crey4fun** [comment]
`AttributeError: 'tuple' object has no attribute 'app_id'`

Looks like your "game" variable is a tuple instead of a GameOption. Where did you define it?

**Comment by mninc** [comment]
reinstalling steampy fixed it, my bad
